"""Delete creation_date  to Task

Revision ID: 29db89cc46b8
Revises: 9df0ad28d4fd
Create Date: 2024-03-01 21:34:30.708039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29db89cc46b8'
down_revision = '9df0ad28d4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectRole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('projectrole')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', mysql.DATETIME(), nullable=False))

    op.create_table('projectrole',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('projectId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], name='projectrole_ibfk_1'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='projectrole_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('projectRole')
    # ### end Alembic commands ###
