"""Add required initial data

Revision ID: d880a7e1c5f7
Revises: 9df0ad28d4fd
Create Date: 2024-03-26 01:07:58.880291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd880a7e1c5f7'
down_revision = '9df0ad28d4fd'
branch_labels = None
depends_on = None


def upgrade():
    # (здесь будут другие автоматически сгенерированные команды)
    # ### end Alembic commands ###

    # Добавление обязательных данных
    op.execute("INSERT INTO status_list (statusName, description) VALUES ('pending', 'Waiting for processing')")
    op.execute("INSERT INTO status_list (statusName, description) VALUES ('in_progress', 'Currently in progress')")
    op.execute("INSERT INTO status_list (statusName, description) VALUES ('done', 'Task completed')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # (здесь будут другие автоматически сгенерированные команды)
    # ### end Alembic commands ###

    # Удаление обязательных данных
    op.execute("DELETE FROM status_list WHERE statusName IN ('pending', 'in_progress', 'done')")
